name: BuildFFA
version: 0.18.18c
description: BuildFFA is a FreeForAll-Game, where you drop on the map and you have blocks.

author: Snocember
website: https://dev.snocember.de
# The two above notes must not be removed.

main: de.snocember.buildffa.Main
database: false

commands:
  buildffa:
    aliases: [bffa, game]
    description: The main game command.
  stats:
    description: See your stats.
  kit:
    aliases: [kits]
    description: Choose your kit.
