name: BuildFFA
version: 0.18.19c
description: BuildFFA is a FreeForAll-Game, where you drop on the map and you have blocks.

author: Snocember
website: https://dev.snocember.de
# Please keep the credit above — it is shown with /version BuildFFA.
# GPLv3 requires attribution. Feel free to add yourself, just don’t remove the note.

main: de.snocember.buildffa.Main
database: false

commands:
  buildffa:
    aliases: [bffa, game]
    description: The main game command.
  stats:
    description: See your stats.
  kit:
    aliases: [kits]
    description: Choose your kit.
